### ISSUE TITLE
没有词库

### ISSUE THREAD

**Issue by ytianxia6** [aardio/wubi-lex#1]
介绍说已经内置了大量码表，包含极点、QQ等。我下载后只有系统码表（86）， 96， 86三个码表。
其他码表没有内置。
请问我可以在哪里下载？

**Comment by aardio** [comment]
看不到新的码表 - 是因为你从旧版升级过来，
软件升级不能未经你自己的操作删除原来的码表。

你可以在码表列表框空白处点右键，在弹出的右键菜单中点“添加码表”，就可以看到更多的新码表了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yhl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 下午2:49
收件人:&nbsp;"aardio/wubi-lex"<wubi-lex@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aardio/wubi-lex] 没有词库 (#1)





 
介绍说已经内置了大量码表，包含极点、QQ等。我下载后只有系统码表（86）， 96， 86三个码表。
 其他码表没有内置。
 请问我可以在哪里下载？

**Comment by aardio** [comment]
新版已经做了改进，直接点「添加码表」按钮即可
![image](https://user-images.githubusercontent.com/14340891/77186849-7f704600-6b0e-11ea-934f-9dac2eef3e17.png)
