### ISSUE TITLE
有办法删除已经安装的码表吗？安装后很多字打不出来。。。

### ISSUE THREAD

**Issue by piaolin** [aardio/wubi-lex#14]
有办法删除已经安装的码表吗？安装后很多字打不出来。。。建议大家还是先别安装。。。。

**Comment by aardio** [comment]
具体是什么码表，安装后你什么字打不出来？！ 你又是怎么打的这个字呢？
百度贴吧有六百多回复了，基本都用得很好，为什么大家就不能安装呢？！wubiLex 只是一个码表替换工具，不会破坏输入法。

**Comment by piaolin** [comment]
我就安装了 “五笔98完整版”，
结果，“没”，“不”等都打不出来了，也没有找到删除码表按钮，能提供删除方法吗？

**Comment by aardio** [comment]
1、任何码表都不一定跟你原来使用的码表完全一致。如果你不适应其他码表，请换成你自己熟悉的码表。
2、任何输入法都不提供「删除码表」的功能。微软五笔本来就不支持五笔98， wubiLex 提供了恢复默认五笔86码表的功能。

**Comment by piaolin** [comment]
怎么提前不说。。。很多都没办法输出来了，真的烦。。。。。。。。。。。。。。
你这个添加码表的原理是什么？我试试能不能逆向操作。。

**Comment by aardio** [comment]
1、你要我提前跟你说什么呢？！刚学五笔吗？！你不知道不同码表有差别？！
2、很多字打不出来，具体你是怎么打的，五笔86、98是不是分不清楚？！
3、安装你原来的码表就是逆向操作，这需要别人教你？！或是你找不到你自己用的码表在哪？！

**Comment by piaolin** [comment]
1。我不知道原来用的码表在哪，可以的话请告诉我
2。我不知道你添加码表是写入文件还是添加文件，可以的话请告诉我，我自己想办法还原，谢谢。

**Comment by aardio** [comment]
1、如果你没有替换过码表，默认码表就是「微软五笔86」，安装回去就恢复了，如果你86、98分不清楚，字当然打不出来。
2、如果你之前用其他软件替换过，那你的码表哪里来的，那就上哪找， wubiLex 提供了浏览查看、导出备份系统码表的功能，你也可以用 wubiLex 备份你自用的码表，如果你忘记了备份 - 嗯，放心大家都不会怪你。

**Comment by aardio** [comment]
1、如果你没有替换过码表，默认码表就是「微软五笔86」，安装回去就恢复了，如果你86、98分不清楚，字当然打不出来。
2、如果你之前用其他软件替换过，那你的码表哪里来的，那就上哪找， wubiLex 提供了浏览查看、导出备份系统码表的功能，你也可以用 wubiLex 备份你自用的码表，如果你忘记了备份......

**Comment by piaolin** [comment]
OK感谢，已经恢复了
