### ISSUE TITLE
郑码 - 有没有可能一键切换繁简体？

### ISSUE THREAD

**Issue by rjiang9** [aardio/wubi-lex#2]
英文win10, 我用郑码替换了五笔，非常好用。
还有个问题，
就是有没有可能一键切换繁简体呢？
还是必须切换安装繁体的码表？
那两个繁体的码表好象词汇编码有些不用， 
按简体编码不总能打出想打的词。

**Comment by aardio** [comment]
右键点「编辑码表」，然后右键点编辑器里的码表，再点「简繁转换」即可实现打简出繁




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ray"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 凌晨5:31
收件人:&nbsp;"aardio/wubi-lex"<wubi-lex@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aardio/wubi-lex] 郑码 - 有没有可能一键切换繁简体？ (#2)





 
英文win10, 我用郑码替换了五笔，非常好用。
 还有个问题，
 就是有没有可能一键切换繁简体呢？
 还是必须切换安装繁体的码表？
 那两个繁体的码表好象词汇编码有些不用，
 按简体编码不总能打出想打的词。

**Comment by rjiang9** [comment]
哇，@aardio 我都不知道该怎么感谢您.
