### ISSUE TITLE
这个能切换简繁输入吗

### ISSUE THREAD

**Issue by shuiliu11** [aardio/wubi-lex#3]
默认WIN10 五笔没有繁体输入,这个软件有办法解决吗.具体怎么操作呢,

**Comment by aardio** [comment]
右键编辑码表，在码表编辑器点右键 - 可以切换简体繁体



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shuiliu11"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 凌晨0:44
收件人: "aardio/wubi-lex"<wubi-lex@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [aardio/wubi-lex] 这个能切换简繁输入吗 (#3)





 
默认WIN10 五笔没有繁体输入,这个软件有办法解决吗.具体怎么操作呢,
