### ISSUE TITLE
恢复系统码表

### ISSUE THREAD

**Issue by shuiliu11** [aardio/wubi-lex#4]
我添加了几个码表到系统码表里面,现在想恢复为未安装软件时候的系统码表状态,怎么操作呢

**Comment by aardio** [comment]
wubiLex已经自带了微软五笔默认码表，直接点添加即可，在wubiLex里你也可以查看、浏览、复制、导出系统码表，如果你希望备份系统码表 - 那么可以提前做好备份。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shuiliu11"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 中午12:15
收件人: "aardio/wubi-lex"<wubi-lex@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [aardio/wubi-lex] 恢复系统码表 (#4)





 
我添加了几个码表到系统码表里面,现在想恢复为未安装软件时候的系统码表状态,怎么操作呢

**Comment by aardio** [comment]
如果之前没有备份系统码表也没有关系，wubiLex已经为大家提供了一个微软五笔码表，WIN10本身也有一个微软五笔码表的备份 - 可以用 everything 在C盘搜索文件名：ChsWubi.lex 就能找到 ，再用 wubiLex 替换回去就行了。
