### ISSUE TITLE
能否取消程序的管理权限要求

### ISSUE THREAD

**Issue by doomiris** [aardio/wubi-lex#6]
能否提供一个不需要管理权限的版本.  公司电脑上仅有普通用户权限, 没有管理权限. 😂

**Comment by aardio** [comment]
微软五笔需要管理权限才能替换词库，取消就没法用了。

**Comment by aardio** [comment]
把源码中 main.aardio 第一行的 //RUNAS// 删除，再编译生成EXE就不需要管理权限，但这样就无法正常编辑码表和设置微软五笔了，「超级热键」与「反查」不需要管理权限。

**Comment by doomiris** [comment]
按你说的方法编译了. 我先用着. 感谢!
