### ISSUE TITLE
下载码表失败，请问怎么解决？

### ISSUE THREAD

**Issue by solaris-9** [aardio/wubi-lex#9]
错误如图示
![image](https://user-images.githubusercontent.com/20120949/82629345-04b4cb80-9c22-11ea-9e43-cbb5c772fa68.png)

**Comment by aardio** [comment]
我试了是可以下载的，请重试一下看

**Comment by solaris-9** [comment]
确实是不行的，但是用下载网络码表的方式，把程序里面的网址填上去就可以了，可以说非常奇怪了。
